#!/usr/bin/python3


class CfgDefaults:
    # def confs
    config_base = {
        'notes': 'generated by generator.py',
        'seed': '1fe40505e131963c',  # default seed
        'tv-size': None,
        'tv-count': None
    }
    counter_stream = {
        'type': 'counter'
    }
    hw_stream = {
        'type': 'hw_counter',
        'hw': 4
    }
    random_stream = {
        'type': 'pcg32_stream'
    }
    false_stream = {
        'type': 'false_stream'
    }
    rnd_plt_ctx_stream = {
        'type': 'rnd_plt_ctx_stream',
        'source': None
    }
    sac_stream = {
        'type': 'sac'
    }


class FunArgs:
    def __init__(self, block_size, key_size, iv_size=None, rounds=()):
        self.block_size = block_size
        self.key_size = key_size
        self.iv_size = iv_size
        self.rounds = rounds

